language: go
go:
- 1.5
- 1.6
- 1.7
- 1.8
- 1.9
- "1.10"
- 1.11
sudo: required
addons:
  apt:
    packages:
      - docker-ce
cache:
  apt: true
  directories:
  - $HOME/.gimme
env:
  global:
  - GO15VENDOREXPERIMENT=1
install:
- true
script:
- docker build -t "$DOCKER_IMAGE_TAG" .

deploy:
  provider: script
  script: ./.scripts/docker_push.sh
  on:
    branch: master
