language: go
go:
- 1.9
sudo: required
dist: trusty
group: deprecated-2017Q4

services:
  - docker

script:
- docker build -t "$DOCKER_IMAGE_TAG" .

deploy:
  provider: script
  script: ./.scripts/docker_push
  on:
    branch: master
